version: '3.5'

services:

  flask:
    ports:
      - "23:22"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"

  sqlite-web:
    container_name: sqlite-web
    image: coleifer/sqlite-web
    volumes:
      - db:/data
    environment:
      - SQLITE_DATABASE=test.db
    ports:
      - "5001:8080"
